# Generated by Django 4.0.5 on 2022-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
