# Generated by Django 4.0.5 on 2022-07-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='partfolyo',
            name='t_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
